### ISSUE TITLE
Release better .zip as .rar

### ISSUE THREAD

**Issue by CSchmidtDD** [hey8you/Stream-Deck-and-MSFS-2020#3]
Hey @hey8you, thanks for your great idea with the icons on the flight sim for the Stream Deck! 👍 

The next time you release, could you remove the rar and pack the collection into a zip?
This way, it would be much more accessible.

Also, I try to add a few icons when I find the time and open a pull request for you, if that's alright with you.

Best Regards

**Comment by hey8you** [comment]
Not a problem, I can use zip.

"Also, I try to add a few icons when I find the time and open a pull request for you, if that's alright with you."
I have no problem with that.

**Comment by hey8you** [comment]
New and all releases after will be on .ZIP
